# This workflow validates the canonical hash of the SQLite RAG cache.
# The hash is stored in sigil_rag_cache.hash and should match the database.

name: Validate DB Hash

on:
  push:
    paths:
      - '**/sigil_rag_cache.db'
      - '**/sigil_rag_cache.hash'
      - '.github/workflows/validate-db-hash.yml'
  workflow_dispatch:

jobs:
  validate-db-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate DB hash
        run: |
          if [ ! -f "sigil_rag_cache.db" ]; then
            echo "❌ Database file not found"
            exit 1
          fi
          if [ ! -f "sigil_rag_cache.hash" ]; then
            echo "❌ Hash file not found"
            exit 1
          fi
          python audits/validate_db_hash.py --db sigil_rag_cache.db --expected-hash "$(cat sigil_rag_cache.hash)"
